export interface CuratedRecipe {
  id: string;
  name: string;
  mealType: 'breakfast' | 'lunch' | 'dinner' | 'snack';
  prepTime: number;
  emoji: string;
  ingredients: { name: string; quantity: string; unit: string }[];
  steps: string[];
}

export const CURATED_RECIPES: CuratedRecipe[] = [
  {
    id: 'curated_pancakes',
    name: 'Pancakes',
    mealType: 'breakfast',
    prepTime: 20,
    emoji: '🥞',
    ingredients: [
      { name: 'flour', quantity: '1.5', unit: 'cups' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'eggs', quantity: '2', unit: 'pieces' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix flour, sugar, and baking powder in a large bowl.',
      'Whisk together milk, eggs, and melted butter in a separate bowl.',
      'Combine wet and dry ingredients, stirring until just smooth.',
      'Heat a non-stick pan over medium heat and pour 1/4 cup batter per pancake.',
      'Cook until bubbles form, flip, and cook 1–2 more minutes. Serve warm.',
    ],
  },
  {
    id: 'curated_scrambled_eggs',
    name: 'Scrambled Eggs',
    mealType: 'breakfast',
    prepTime: 10,
    emoji: '🍳',
    ingredients: [
      { name: 'eggs', quantity: '4', unit: 'pieces' },
      { name: 'milk', quantity: '3', unit: 'tbsp' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '0.25', unit: 'tsp' },
    ],
    steps: [
      'Crack eggs into a bowl, add milk and salt, and whisk until combined.',
      'Melt butter in a non-stick skillet over low heat.',
      'Pour in egg mixture and gently fold with a spatula as it sets.',
      'Remove from heat while still slightly glossy. Serve immediately.',
    ],
  },
  {
    id: 'curated_oatmeal',
    name: 'Oatmeal',
    mealType: 'breakfast',
    prepTime: 10,
    emoji: '🥣',
    ingredients: [
      { name: 'oats', quantity: '1', unit: 'cup' },
      { name: 'milk', quantity: '2', unit: 'cups' },
      { name: 'banana', quantity: '1', unit: 'piece' },
      { name: 'honey', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Bring milk to a simmer in a saucepan over medium heat.',
      'Stir in oats and cook for 5 minutes, stirring occasionally.',
      'Remove from heat, top with sliced banana and drizzle with honey.',
    ],
  },
  {
    id: 'curated_avocado_toast',
    name: 'Avocado Toast',
    mealType: 'breakfast',
    prepTime: 10,
    emoji: '🥑',
    ingredients: [
      { name: 'bread', quantity: '2', unit: 'slices' },
      { name: 'avocado', quantity: '1', unit: 'piece' },
      { name: 'lemon', quantity: '0.5', unit: 'piece' },
      { name: 'salt', quantity: '0.25', unit: 'tsp' },
      { name: 'eggs', quantity: '2', unit: 'pieces' },
    ],
    steps: [
      'Toast bread slices until golden and crisp.',
      'Mash avocado with lemon juice and salt in a bowl.',
      'Spread avocado mixture generously over toast.',
      'Top with a fried or poached egg. Season with extra salt and pepper.',
    ],
  },
  {
    id: 'curated_caesar_salad',
    name: 'Caesar Salad',
    mealType: 'lunch',
    prepTime: 15,
    emoji: '🥗',
    ingredients: [
      { name: 'romaine lettuce', quantity: '1', unit: 'head' },
      { name: 'parmesan cheese', quantity: '0.5', unit: 'cup' },
      { name: 'croutons', quantity: '1', unit: 'cup' },
      { name: 'Caesar dressing', quantity: '3', unit: 'tbsp' },
      { name: 'lemon', quantity: '0.5', unit: 'piece' },
    ],
    steps: [
      'Chop romaine lettuce into bite-sized pieces and place in a large bowl.',
      'Drizzle Caesar dressing over lettuce and toss to coat evenly.',
      'Add croutons and shaved parmesan cheese.',
      'Squeeze lemon juice over the top and serve immediately.',
    ],
  },
  {
    id: 'curated_chicken_tacos',
    name: 'Chicken Tacos',
    mealType: 'lunch',
    prepTime: 25,
    emoji: '🌮',
    ingredients: [
      { name: 'chicken breast', quantity: '400', unit: 'g' },
      { name: 'taco shells', quantity: '8', unit: 'pieces' },
      { name: 'onion', quantity: '1', unit: 'piece' },
      { name: 'tomato', quantity: '2', unit: 'pieces' },
      { name: 'lettuce', quantity: '2', unit: 'cups' },
      { name: 'cheese', quantity: '0.5', unit: 'cup' },
      { name: 'taco seasoning', quantity: '1', unit: 'tbsp' },
      { name: 'oil', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Season chicken with taco seasoning on both sides.',
      'Cook chicken in oil over medium-high heat for 6–7 minutes per side.',
      'Let rest 5 minutes, then slice thinly.',
      'Warm taco shells in the oven for 3 minutes.',
      'Fill shells with chicken, diced tomato, onion, lettuce, and cheese.',
    ],
  },
  {
    id: 'curated_club_sandwich',
    name: 'Club Sandwich',
    mealType: 'lunch',
    prepTime: 15,
    emoji: '🥪',
    ingredients: [
      { name: 'bread', quantity: '3', unit: 'slices' },
      { name: 'chicken breast', quantity: '100', unit: 'g' },
      { name: 'bacon', quantity: '2', unit: 'strips' },
      { name: 'lettuce', quantity: '2', unit: 'leaves' },
      { name: 'tomato', quantity: '1', unit: 'piece' },
      { name: 'mayonnaise', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Toast all bread slices until golden.',
      'Cook bacon until crispy; pan-fry or slice cooked chicken.',
      'Spread mayonnaise on all toast slices.',
      'Layer the bottom slice with lettuce, tomato, and chicken.',
      'Add middle slice, then bacon and remaining lettuce. Top with final slice. Cut diagonally.',
    ],
  },
  {
    id: 'curated_veggie_wrap',
    name: 'Veggie Wrap',
    mealType: 'lunch',
    prepTime: 12,
    emoji: '🌯',
    ingredients: [
      { name: 'flour tortilla', quantity: '2', unit: 'pieces' },
      { name: 'avocado', quantity: '1', unit: 'piece' },
      { name: 'carrot', quantity: '1', unit: 'piece' },
      { name: 'lettuce', quantity: '2', unit: 'cups' },
      { name: 'tomato', quantity: '1', unit: 'piece' },
      { name: 'cheese', quantity: '0.5', unit: 'cup' },
      { name: 'hummus', quantity: '3', unit: 'tbsp' },
    ],
    steps: [
      'Spread hummus evenly over each tortilla.',
      'Slice avocado and shred carrot.',
      'Layer lettuce, tomato, avocado, carrot, and cheese down the centre.',
      'Roll tortilla tightly, slice in half, and serve.',
    ],
  },
  {
    id: 'curated_grilled_chicken',
    name: 'Grilled Chicken',
    mealType: 'dinner',
    prepTime: 30,
    emoji: '🍗',
    ingredients: [
      { name: 'chicken breast', quantity: '600', unit: 'g' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'lemon', quantity: '1', unit: 'piece' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'paprika', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Marinate chicken with olive oil, minced garlic, lemon juice, salt, and paprika for 20 minutes.',
      'Preheat grill or grill pan to medium-high heat.',
      'Grill chicken for 6–7 minutes per side until cooked through.',
      'Rest for 5 minutes before slicing and serving.',
    ],
  },
  {
    id: 'curated_spaghetti_bolognese',
    name: 'Spaghetti Bolognese',
    mealType: 'dinner',
    prepTime: 40,
    emoji: '🍝',
    ingredients: [
      { name: 'spaghetti', quantity: '400', unit: 'g' },
      { name: 'ground beef', quantity: '500', unit: 'g' },
      { name: 'tomato', quantity: '400', unit: 'g' },
      { name: 'onion', quantity: '1', unit: 'piece' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté diced onion and garlic in oil until soft.',
      'Add ground beef and cook until browned, breaking it apart.',
      'Stir in tomato paste, crushed tomatoes, salt, and oregano. Simmer 20 minutes.',
      'Cook spaghetti in salted boiling water according to package instructions.',
      'Drain pasta and toss with sauce. Serve with parmesan.',
    ],
  },
  {
    id: 'curated_chicken_stew',
    name: 'Chicken Stew',
    mealType: 'dinner',
    prepTime: 50,
    emoji: '🫕',
    ingredients: [
      { name: 'chicken thighs', quantity: '600', unit: 'g' },
      { name: 'potato', quantity: '3', unit: 'pieces' },
      { name: 'carrot', quantity: '2', unit: 'pieces' },
      { name: 'onion', quantity: '1', unit: 'piece' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'chicken broth', quantity: '3', unit: 'cups' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Brown chicken thighs in oil in a large pot, then set aside.',
      'Sauté onion and garlic until fragrant.',
      'Add diced potatoes, carrots, and chicken back to pot.',
      'Pour in chicken broth, bring to boil, then simmer 30 minutes.',
      'Season to taste and serve hot.',
    ],
  },
  {
    id: 'curated_baked_salmon',
    name: 'Baked Salmon',
    mealType: 'dinner',
    prepTime: 25,
    emoji: '🐟',
    ingredients: [
      { name: 'salmon fillet', quantity: '600', unit: 'g' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'lemon', quantity: '1', unit: 'piece' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'fresh dill', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '0.5', unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 200°C (400°F). Line a baking tray with parchment.',
      'Place salmon on tray, drizzle with oil, and season with salt.',
      'Top with minced garlic, lemon slices, and fresh dill.',
      'Bake for 15–18 minutes until salmon flakes easily. Serve with rice or vegetables.',
    ],
  },
  {
    id: 'curated_beef_stir_fry',
    name: 'Beef Stir Fry',
    mealType: 'dinner',
    prepTime: 25,
    emoji: '🥩',
    ingredients: [
      { name: 'beef sirloin', quantity: '400', unit: 'g' },
      { name: 'broccoli', quantity: '2', unit: 'cups' },
      { name: 'carrot', quantity: '1', unit: 'piece' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'rice', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Slice beef thinly and marinate in 1 tbsp soy sauce for 10 minutes.',
      'Cook rice according to package instructions.',
      'Heat oil in a wok over high heat and stir-fry beef until browned. Remove.',
      'Stir-fry broccoli and carrot in the same wok for 3 minutes.',
      'Return beef, add remaining soy sauce and garlic, toss for 2 minutes. Serve over rice.',
    ],
  },
  {
    id: 'curated_lentil_soup',
    name: 'Lentil Soup',
    mealType: 'dinner',
    prepTime: 35,
    emoji: '🍲',
    ingredients: [
      { name: 'red lentils', quantity: '1.5', unit: 'cups' },
      { name: 'onion', quantity: '1', unit: 'piece' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'carrot', quantity: '2', unit: 'pieces' },
      { name: 'tomato', quantity: '2', unit: 'pieces' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'vegetable broth', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Sauté diced onion, garlic, and carrot in olive oil until softened.',
      'Add cumin and cook 1 minute until fragrant.',
      'Stir in rinsed lentils, diced tomatoes, and broth. Bring to a boil.',
      'Reduce heat and simmer for 20 minutes until lentils are very soft.',
      'Blend partially for a creamy texture. Season and serve with crusty bread.',
    ],
  },
  {
    id: 'curated_apple_peanut_butter',
    name: 'Apple & Peanut Butter',
    mealType: 'snack',
    prepTime: 5,
    emoji: '🍎',
    ingredients: [
      { name: 'apple', quantity: '2', unit: 'pieces' },
      { name: 'peanut butter', quantity: '4', unit: 'tbsp' },
    ],
    steps: [
      'Wash and core the apples, then slice into wedges.',
      'Serve alongside peanut butter for dipping.',
    ],
  },
  {
    id: 'curated_cheese_crackers',
    name: 'Cheese & Crackers',
    mealType: 'snack',
    prepTime: 5,
    emoji: '🧀',
    ingredients: [
      { name: 'crackers', quantity: '20', unit: 'pieces' },
      { name: 'cheese', quantity: '150', unit: 'g' },
    ],
    steps: [
      'Slice cheese into thin pieces.',
      'Arrange crackers on a plate and top each with a slice of cheese. Serve.',
    ],
  },
  {
    id: 'curated_veggies_hummus',
    name: 'Veggies & Hummus',
    mealType: 'snack',
    prepTime: 10,
    emoji: '🥕',
    ingredients: [
      { name: 'carrot', quantity: '2', unit: 'pieces' },
      { name: 'cucumber', quantity: '1', unit: 'piece' },
      { name: 'celery', quantity: '3', unit: 'stalks' },
      { name: 'hummus', quantity: '0.5', unit: 'cup' },
    ],
    steps: [
      'Peel and cut carrots, cucumber, and celery into sticks.',
      'Arrange veggie sticks on a plate with a bowl of hummus for dipping.',
    ],
  },
  {
    id: 'curated_banana_smoothie',
    name: 'Banana Smoothie',
    mealType: 'snack',
    prepTime: 5,
    emoji: '🍌',
    ingredients: [
      { name: 'banana', quantity: '2', unit: 'pieces' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'yogurt', quantity: '0.5', unit: 'cup' },
      { name: 'honey', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Peel and slice bananas.',
      'Add bananas, milk, yogurt, and honey to a blender.',
      'Blend until smooth and creamy. Pour into glasses and serve immediately.',
    ],
  },
];
