export interface CuratedRecipe {
  id: string;
  name: string;
  mealType: 'breakfast' | 'lunch' | 'dinner' | 'snack';
  prepTime: number;
  emoji: string;
  ingredients: { name: string; quantity: string; unit: string }[];
  steps: string[];
}

export const CURATED_RECIPES: CuratedRecipe[] = [

  // ── BREAKFAST (16 options) ─────────────────────────────────────────────────

  {
    id: 'curated_oatmeal_cholesterol',
    name: 'Oatmeal "Cholesterol Buster"',
    mealType: 'breakfast',
    prepTime: 10,
    emoji: '🫐',
    ingredients: [
      { name: 'rolled oats', quantity: '0.5', unit: 'cup' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'cinnamon', quantity: '0.5', unit: 'tsp' },
      { name: 'strawberries', quantity: '0.5', unit: 'cup' },
    ],
    steps: [
      'Bring water to a boil in a small saucepan.',
      'Stir in oats and cook for 5 minutes, stirring occasionally.',
      'Top with cinnamon and sliced strawberries.',
    ],
  },
  {
    id: 'curated_greek_yogurt_bowl',
    name: 'Greek Yogurt Bowl',
    mealType: 'breakfast',
    prepTime: 5,
    emoji: '🫙',
    ingredients: [
      { name: '0% fat Greek yogurt', quantity: '1', unit: 'cup' },
      { name: 'blueberries', quantity: '0.5', unit: 'cup' },
    ],
    steps: [
      'Spoon Greek yogurt into a bowl.',
      'Top with fresh blueberries and serve immediately.',
    ],
  },
  {
    id: 'curated_apple_cinnamon_oatmeal',
    name: 'Apple Cinnamon Oatmeal',
    mealType: 'breakfast',
    prepTime: 12,
    emoji: '🍎',
    ingredients: [
      { name: 'rolled oats', quantity: '0.5', unit: 'cup' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'apple', quantity: '0.5', unit: 'medium' },
      { name: 'cinnamon', quantity: '0.5', unit: 'tsp' },
    ],
    steps: [
      'Cook oats in water for 5 minutes.',
      'Dice the apple and stir it in during the last 2 minutes.',
      'Sprinkle with cinnamon before serving.',
    ],
  },
  {
    id: 'curated_cottage_cheese_plate',
    name: 'Cottage Cheese Plate',
    mealType: 'breakfast',
    prepTime: 5,
    emoji: '🥒',
    ingredients: [
      { name: 'low-fat cottage cheese', quantity: '0.75', unit: 'cup' },
      { name: 'cucumber', quantity: '0.5', unit: 'medium' },
      { name: 'black pepper', quantity: '0.25', unit: 'tsp' },
    ],
    steps: [
      'Slice cucumber into rounds.',
      'Plate cottage cheese alongside cucumber.',
      'Season with black pepper and serve.',
    ],
  },
  {
    id: 'curated_raspberry_flax_parfait',
    name: 'Raspberry & Flax Parfait',
    mealType: 'breakfast',
    prepTime: 5,
    emoji: '🍓',
    ingredients: [
      { name: '0% Greek yogurt', quantity: '1', unit: 'cup' },
      { name: 'fresh raspberries', quantity: '0.5', unit: 'cup' },
      { name: 'ground flaxseed', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Layer yogurt in a glass or bowl.',
      'Top with raspberries and sprinkle flaxseed over the top.',
    ],
  },
  {
    id: 'curated_chia_seed_pudding',
    name: 'Chia Seed Pudding',
    mealType: 'breakfast',
    prepTime: 5,
    emoji: '🫐',
    ingredients: [
      { name: 'chia seeds', quantity: '3', unit: 'tbsp' },
      { name: 'almond milk', quantity: '1', unit: 'cup' },
      { name: 'mixed berries', quantity: '0.5', unit: 'cup' },
    ],
    steps: [
      'Mix chia seeds with almond milk in a jar.',
      'Refrigerate for at least 4 hours or overnight.',
      'Top with mixed berries before serving.',
    ],
  },
  {
    id: 'curated_veggie_egg_white_omelet',
    name: 'Veggie Egg White Omelet',
    mealType: 'breakfast',
    prepTime: 10,
    emoji: '🥚',
    ingredients: [
      { name: 'egg whites', quantity: '4', unit: 'large' },
      { name: 'spinach', quantity: '1', unit: 'cup' },
      { name: 'mushrooms', quantity: '0.5', unit: 'cup' },
    ],
    steps: [
      'Whisk egg whites with a pinch of salt.',
      'Sauté spinach and mushrooms in a non-stick pan for 2 minutes.',
      'Pour egg whites over vegetables and cook until set. Fold and serve.',
    ],
  },
  {
    id: 'curated_turkey_grapefruit_plate',
    name: 'Turkey & Grapefruit Plate',
    mealType: 'breakfast',
    prepTime: 5,
    emoji: '🍊',
    ingredients: [
      { name: 'lean turkey breast slices', quantity: '3', unit: 'oz' },
      { name: 'grapefruit', quantity: '0.5', unit: 'large' },
    ],
    steps: [
      'Arrange turkey slices on a plate.',
      'Halve and segment the grapefruit alongside.',
    ],
  },
  {
    id: 'curated_turkey_cucumber_rollups',
    name: 'Turkey & Cucumber Roll-ups',
    mealType: 'breakfast',
    prepTime: 5,
    emoji: '🥙',
    ingredients: [
      { name: 'sliced turkey breast', quantity: '4', unit: 'slices' },
      { name: 'cucumber', quantity: '1', unit: 'medium' },
    ],
    steps: [
      'Cut cucumber into spears.',
      'Wrap each cucumber spear with a turkey slice and serve.',
    ],
  },
  {
    id: 'curated_turkey_bacon_avocado',
    name: 'Turkey Bacon & Avocado Plate',
    mealType: 'breakfast',
    prepTime: 10,
    emoji: '🥑',
    ingredients: [
      { name: 'lean turkey bacon', quantity: '3', unit: 'strips' },
      { name: 'avocado', quantity: '0.5', unit: 'medium' },
      { name: 'cherry tomatoes', quantity: '0.5', unit: 'cup' },
      { name: 'black pepper', quantity: '0.25', unit: 'tsp' },
    ],
    steps: [
      'Cook turkey bacon in a non-stick pan until crispy.',
      'Slice avocado and halve cherry tomatoes.',
      'Plate everything together and season with black pepper.',
    ],
  },
  {
    id: 'curated_foul_mudammas',
    name: 'Foul Mudammas Bowl',
    mealType: 'breakfast',
    prepTime: 10,
    emoji: '🫘',
    ingredients: [
      { name: 'fava beans (canned)', quantity: '1', unit: 'cup' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'cumin', quantity: '0.5', unit: 'tsp' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
      { name: 'fresh parsley', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Warm fava beans in a saucepan over medium heat.',
      'Mash lightly with a fork and stir in minced garlic, cumin, and olive oil.',
      'Top with fresh parsley and serve.',
    ],
  },
  {
    id: 'curated_mediterranean_tofu_scramble',
    name: 'Mediterranean Tofu Scramble',
    mealType: 'breakfast',
    prepTime: 12,
    emoji: '🌿',
    ingredients: [
      { name: 'firm tofu', quantity: '6', unit: 'oz' },
      { name: 'spinach', quantity: '1', unit: 'cup' },
      { name: 'cherry tomatoes', quantity: '0.5', unit: 'cup' },
      { name: 'cumin', quantity: '0.25', unit: 'tsp' },
      { name: 'turmeric', quantity: '0.25', unit: 'tsp' },
    ],
    steps: [
      'Crumble tofu into a hot non-stick pan.',
      'Add cumin and turmeric, cook for 3 minutes.',
      'Stir in spinach and tomatoes until wilted.',
    ],
  },
  {
    id: 'curated_zaatar_avocado_toast',
    name: "Za'atar Avocado Toast",
    mealType: 'breakfast',
    prepTime: 5,
    emoji: '🥑',
    ingredients: [
      { name: 'low-carb bread', quantity: '1', unit: 'slice' },
      { name: 'avocado', quantity: '0.5', unit: 'medium' },
      { name: "za'atar seasoning", quantity: '1', unit: 'tsp' },
      { name: 'lemon juice', quantity: '0.5', unit: 'tsp' },
    ],
    steps: [
      'Toast the bread slice.',
      'Mash avocado with lemon juice and spread on toast.',
      "Sprinkle za'atar generously on top.",
    ],
  },
  {
    id: 'curated_spicy_chicken_sausage',
    name: 'Spicy Chicken Sausage & Peppers',
    mealType: 'breakfast',
    prepTime: 15,
    emoji: '🌶️',
    ingredients: [
      { name: 'lean chicken sausage', quantity: '2', unit: 'links' },
      { name: 'green bell pepper', quantity: '1', unit: 'medium' },
      { name: 'jalapeños', quantity: '1', unit: 'medium' },
    ],
    steps: [
      'Slice sausage and peppers.',
      'Cook in a non-stick pan over medium heat for 8–10 minutes until sausage is browned.',
      'Serve hot.',
    ],
  },
  {
    id: 'curated_peanut_butter_banana_oatmeal',
    name: 'Peanut Butter Banana Oatmeal',
    mealType: 'breakfast',
    prepTime: 10,
    emoji: '🍌',
    ingredients: [
      { name: 'rolled oats', quantity: '0.5', unit: 'cup' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'powdered peanut butter', quantity: '2', unit: 'tbsp' },
      { name: 'banana', quantity: '0.5', unit: 'medium' },
    ],
    steps: [
      'Cook oats in water for 5 minutes.',
      'Stir in powdered peanut butter.',
      'Top with banana slices and serve.',
    ],
  },
  {
    id: 'curated_blackberry_almond_chia',
    name: 'Blackberry Almond Chia Pudding',
    mealType: 'breakfast',
    prepTime: 5,
    emoji: '🫐',
    ingredients: [
      { name: 'chia seeds', quantity: '3', unit: 'tbsp' },
      { name: 'almond milk', quantity: '1', unit: 'cup' },
      { name: 'blackberries', quantity: '0.5', unit: 'cup' },
      { name: 'sliced almonds', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Mix chia seeds with almond milk and refrigerate overnight.',
      'Top with blackberries and sliced almonds before serving.',
    ],
  },

  // ── LUNCH (20 options) ──────────────────────────────────────────────────────

  {
    id: 'curated_chicken_burrito_bowl',
    name: 'Chicken Burrito Bowl',
    mealType: 'lunch',
    prepTime: 20,
    emoji: '🌯',
    ingredients: [
      { name: 'cauliflower rice', quantity: '1', unit: 'cup' },
      { name: 'grilled chicken breast', quantity: '4', unit: 'oz' },
      { name: 'salsa', quantity: '3', unit: 'tbsp' },
      { name: 'bell peppers', quantity: '0.5', unit: 'cup' },
      { name: 'white onion', quantity: '0.25', unit: 'cup' },
    ],
    steps: [
      'Rice cauliflower and cook in a pan for 5 minutes.',
      'Season and grill chicken breast, then slice.',
      'Assemble bowl with cauliflower rice, chicken, peppers, onion, and salsa.',
    ],
  },
  {
    id: 'curated_salmon_lemon_bowl',
    name: 'Salmon & Lemon Bowl',
    mealType: 'lunch',
    prepTime: 25,
    emoji: '🐟',
    ingredients: [
      { name: 'quinoa', quantity: '0.5', unit: 'cup' },
      { name: 'salmon fillet', quantity: '4', unit: 'oz' },
      { name: 'dill', quantity: '1', unit: 'tsp' },
      { name: 'broccoli florets', quantity: '1', unit: 'cup' },
      { name: 'cucumber', quantity: '0.5', unit: 'medium' },
    ],
    steps: [
      'Cook quinoa according to package instructions.',
      'Bake salmon at 200°C for 12–15 minutes with dill and lemon.',
      'Steam broccoli. Assemble bowl and serve.',
    ],
  },
  {
    id: 'curated_chicken_fried_rice_bowl',
    name: 'Chicken "Fried Rice" Bowl',
    mealType: 'lunch',
    prepTime: 20,
    emoji: '🍚',
    ingredients: [
      { name: 'cauliflower rice', quantity: '1', unit: 'cup' },
      { name: 'diced chicken breast', quantity: '4', unit: 'oz' },
      { name: 'peas', quantity: '0.25', unit: 'cup' },
      { name: 'carrots', quantity: '0.25', unit: 'cup' },
      { name: 'ginger', quantity: '0.5', unit: 'tsp' },
      { name: 'low-sodium soy sauce', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Stir-fry chicken in a hot pan until cooked through.',
      'Add cauliflower rice, peas, carrots, and ginger.',
      'Splash in soy sauce and stir-fry for 5 more minutes.',
    ],
  },
  {
    id: 'curated_chicken_lentil_herb_bowl',
    name: 'Chicken & Lentil Herb Bowl',
    mealType: 'lunch',
    prepTime: 30,
    emoji: '🥗',
    ingredients: [
      { name: 'green lentils', quantity: '0.5', unit: 'cup' },
      { name: 'grilled chicken breast', quantity: '4', unit: 'oz' },
      { name: 'spinach', quantity: '1', unit: 'cup' },
      { name: 'diced tomatoes', quantity: '0.5', unit: 'cup' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Cook lentils for 20 minutes until tender.',
      'Grill and slice chicken.',
      'Toss everything with lemon juice vinaigrette and serve.',
    ],
  },
  {
    id: 'curated_mediterranean_chicken_bowl',
    name: 'Mediterranean Chicken Bowl',
    mealType: 'lunch',
    prepTime: 25,
    emoji: '🫒',
    ingredients: [
      { name: 'quinoa', quantity: '0.5', unit: 'cup' },
      { name: 'lemon-garlic chicken breast', quantity: '4', unit: 'oz' },
      { name: 'tomato', quantity: '0.5', unit: 'medium' },
      { name: 'cucumber', quantity: '0.5', unit: 'medium' },
      { name: 'kalamata olives', quantity: '6', unit: 'pieces' },
    ],
    steps: [
      'Cook quinoa and set aside.',
      'Marinate chicken in lemon and garlic, then grill.',
      'Assemble bowl with all ingredients.',
    ],
  },
  {
    id: 'curated_spicy_salmon_bowl',
    name: 'Spicy Salmon Bowl',
    mealType: 'lunch',
    prepTime: 25,
    emoji: '🌶️',
    ingredients: [
      { name: 'cauliflower rice', quantity: '1', unit: 'cup' },
      { name: 'salmon fillet', quantity: '4', unit: 'oz' },
      { name: 'cajun seasoning', quantity: '1', unit: 'tsp' },
      { name: 'roasted bell peppers', quantity: '0.5', unit: 'cup' },
      { name: 'zucchini', quantity: '0.5', unit: 'medium' },
    ],
    steps: [
      'Rub salmon with cajun seasoning and bake at 200°C for 14 minutes.',
      'Roast bell peppers and zucchini in the same oven.',
      'Serve over cauliflower rice.',
    ],
  },
  {
    id: 'curated_turkey_lentil_power_bowl',
    name: 'Turkey & Lentil Power Bowl',
    mealType: 'lunch',
    prepTime: 25,
    emoji: '💪',
    ingredients: [
      { name: 'green lentils', quantity: '0.5', unit: 'cup' },
      { name: 'lean ground turkey', quantity: '4', unit: 'oz' },
      { name: 'spinach', quantity: '1', unit: 'cup' },
      { name: 'shredded carrots', quantity: '0.25', unit: 'cup' },
    ],
    steps: [
      'Cook lentils until tender.',
      'Brown ground turkey in a pan.',
      'Combine everything with spinach and shredded carrots.',
    ],
  },
  {
    id: 'curated_tuna_nomayo_salad',
    name: 'Tuna "No-Mayo" Salad',
    mealType: 'lunch',
    prepTime: 10,
    emoji: '🥗',
    ingredients: [
      { name: 'canned tuna (in water)', quantity: '4', unit: 'oz' },
      { name: 'yellow mustard', quantity: '1', unit: 'tsp' },
      { name: 'celery', quantity: '2', unit: 'stalks' },
      { name: 'spinach', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Drain and flake tuna into a bowl.',
      'Mix in mustard and diced celery.',
      'Serve over a bed of spinach.',
    ],
  },
  {
    id: 'curated_southwest_chicken_salad',
    name: 'Southwest Chicken Salad',
    mealType: 'lunch',
    prepTime: 20,
    emoji: '🥙',
    ingredients: [
      { name: 'mixed greens', quantity: '2', unit: 'cups' },
      { name: 'grilled chicken breast', quantity: '4', unit: 'oz' },
      { name: 'salsa', quantity: '3', unit: 'tbsp' },
      { name: 'black beans', quantity: '0.25', unit: 'cup' },
    ],
    steps: [
      'Grill and slice chicken.',
      'Toss greens with black beans.',
      'Top with chicken and use salsa as dressing.',
    ],
  },
  {
    id: 'curated_asian_turkey_lettuce_cups',
    name: 'Asian Turkey Lettuce Cups',
    mealType: 'lunch',
    prepTime: 15,
    emoji: '🥬',
    ingredients: [
      { name: 'ground turkey', quantity: '4', unit: 'oz' },
      { name: 'ginger', quantity: '0.5', unit: 'tsp' },
      { name: 'low-sodium soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'romaine lettuce leaves', quantity: '4', unit: 'large' },
    ],
    steps: [
      'Cook ground turkey with ginger and soy sauce.',
      'Spoon into romaine lettuce leaves and serve.',
    ],
  },
  {
    id: 'curated_chicken_pesto_bowl',
    name: 'Chicken Pesto Bowl',
    mealType: 'lunch',
    prepTime: 20,
    emoji: '🌿',
    ingredients: [
      { name: 'cauliflower rice', quantity: '1', unit: 'cup' },
      { name: 'grilled chicken breast', quantity: '4', unit: 'oz' },
      { name: 'spinach', quantity: '1', unit: 'cup' },
      { name: 'cherry tomatoes', quantity: '0.5', unit: 'cup' },
      { name: 'basil pesto', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Cook cauliflower rice and stir in pesto.',
      'Slice grilled chicken and layer over rice.',
      'Top with spinach and cherry tomatoes.',
    ],
  },
  {
    id: 'curated_salmon_sushi_bowl',
    name: 'Salmon "Sushi" Bowl',
    mealType: 'lunch',
    prepTime: 20,
    emoji: '🍣',
    ingredients: [
      { name: 'cauliflower rice', quantity: '1', unit: 'cup' },
      { name: 'cooked salmon', quantity: '4', unit: 'oz' },
      { name: 'cucumber', quantity: '0.5', unit: 'medium' },
      { name: 'shredded carrots', quantity: '0.25', unit: 'cup' },
      { name: 'nori sheet', quantity: '1', unit: 'piece' },
    ],
    steps: [
      'Season cauliflower rice with a splash of rice vinegar.',
      'Flake cooked salmon and arrange over rice.',
      'Add cucumber sticks, carrots, and torn nori.',
    ],
  },
  {
    id: 'curated_beef_cabbage_bowl',
    name: 'Beef Un-Stuffed Cabbage Bowl',
    mealType: 'lunch',
    prepTime: 25,
    emoji: '🥩',
    ingredients: [
      { name: 'chopped cabbage', quantity: '2', unit: 'cups' },
      { name: 'lean ground beef', quantity: '4', unit: 'oz' },
      { name: 'diced tomatoes', quantity: '0.5', unit: 'cup' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'white onion', quantity: '0.25', unit: 'cup' },
    ],
    steps: [
      'Brown beef with garlic and onion in a large pan.',
      'Add cabbage and tomatoes, cover and cook for 10 minutes.',
      'Season with salt and pepper and serve.',
    ],
  },
  {
    id: 'curated_chicken_kebab_bowl',
    name: 'Chicken Kebab Bowl',
    mealType: 'lunch',
    prepTime: 25,
    emoji: '🍢',
    ingredients: [
      { name: 'quinoa', quantity: '0.5', unit: 'cup' },
      { name: 'chicken breast', quantity: '4', unit: 'oz' },
      { name: 'cucumber', quantity: '0.5', unit: 'medium' },
      { name: 'tzatziki', quantity: '2', unit: 'tbsp' },
      { name: 'tomatoes', quantity: '0.5', unit: 'cup' },
    ],
    steps: [
      'Thread chicken onto skewers and grill for 12–15 minutes.',
      'Serve over quinoa with cucumber, tomatoes, and tzatziki.',
    ],
  },
  {
    id: 'curated_spicy_chicken_shawarma_bowl',
    name: 'Spicy Chicken Shawarma Bowl',
    mealType: 'lunch',
    prepTime: 20,
    emoji: '🧆',
    ingredients: [
      { name: 'cauliflower rice', quantity: '1', unit: 'cup' },
      { name: 'chicken breast', quantity: '4', unit: 'oz' },
      { name: 'shawarma spice blend', quantity: '1', unit: 'tsp' },
      { name: 'cucumber', quantity: '0.5', unit: 'medium' },
      { name: 'tahini', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Coat chicken in shawarma spices and grill.',
      'Slice and serve over cauliflower rice.',
      'Drizzle with tahini and top with cucumber.',
    ],
  },
  {
    id: 'curated_zucchini_noodle_pasta',
    name: 'Zucchini Noodle "Pasta"',
    mealType: 'lunch',
    prepTime: 15,
    emoji: '🍝',
    ingredients: [
      { name: 'zucchini', quantity: '2', unit: 'medium' },
      { name: 'lean ground turkey', quantity: '4', unit: 'oz' },
      { name: 'marinara sauce', quantity: '0.5', unit: 'cup' },
    ],
    steps: [
      'Spiralize zucchini into noodles.',
      'Cook turkey in a pan, then add marinara and simmer for 5 minutes.',
      'Serve sauce over raw or lightly sautéed zucchini noodles.',
    ],
  },
  {
    id: 'curated_lentil_stew',
    name: 'Lentil Stew',
    mealType: 'lunch',
    prepTime: 30,
    emoji: '🫕',
    ingredients: [
      { name: 'brown lentils', quantity: '0.5', unit: 'cup' },
      { name: 'carrots', quantity: '1', unit: 'medium' },
      { name: 'celery', quantity: '2', unit: 'stalks' },
      { name: 'spinach', quantity: '1', unit: 'cup' },
      { name: 'vegetable broth', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Dice carrots and celery and sauté for 3 minutes.',
      'Add lentils and broth, simmer for 20 minutes.',
      'Stir in spinach until wilted and season to taste.',
    ],
  },
  {
    id: 'curated_harissa_chicken_quinoa',
    name: 'Harissa Chicken Quinoa Bowl',
    mealType: 'lunch',
    prepTime: 25,
    emoji: '🌶️',
    ingredients: [
      { name: 'quinoa', quantity: '0.5', unit: 'cup' },
      { name: 'chicken breast', quantity: '4', unit: 'oz' },
      { name: 'harissa paste', quantity: '1', unit: 'tbsp' },
      { name: 'zucchini', quantity: '0.5', unit: 'medium' },
    ],
    steps: [
      'Rub chicken with harissa paste and grill.',
      'Roast zucchini at 200°C for 15 minutes.',
      'Serve over cooked quinoa.',
    ],
  },
  {
    id: 'curated_middle_eastern_turkey_meatball',
    name: 'Middle Eastern Turkey Meatball Bowl',
    mealType: 'lunch',
    prepTime: 30,
    emoji: '🧆',
    ingredients: [
      { name: 'lentils', quantity: '0.5', unit: 'cup' },
      { name: 'lean ground turkey', quantity: '4', unit: 'oz' },
      { name: 'cumin', quantity: '0.5', unit: 'tsp' },
      { name: 'coriander', quantity: '0.25', unit: 'tsp' },
      { name: 'fresh mint', quantity: '1', unit: 'tbsp' },
      { name: 'cucumber', quantity: '0.5', unit: 'medium' },
    ],
    steps: [
      'Mix turkey with cumin and coriander, form into meatballs, and bake at 200°C for 18 minutes.',
      'Cook lentils until tender.',
      'Serve meatballs over lentils with sliced cucumber and fresh mint.',
    ],
  },
  {
    id: 'curated_cauliflower_pizza_bites',
    name: 'Thin-Crust Cauliflower Pizza Bites',
    mealType: 'lunch',
    prepTime: 30,
    emoji: '🍕',
    ingredients: [
      { name: 'cauliflower crust pieces', quantity: '4', unit: 'pieces' },
      { name: 'low-fat mozzarella', quantity: '3', unit: 'tbsp' },
      { name: 'tomato sauce', quantity: '3', unit: 'tbsp' },
      { name: 'fresh basil', quantity: '4', unit: 'leaves' },
    ],
    steps: [
      'Top cauliflower crust with tomato sauce and mozzarella.',
      'Bake at 220°C for 10–12 minutes until golden.',
      'Top with fresh basil and serve.',
    ],
  },

  // ── DINNER (20 options) ─────────────────────────────────────────────────────

  {
    id: 'curated_sheet_pan_lemon_chicken',
    name: 'Sheet Pan Lemon Chicken',
    mealType: 'dinner',
    prepTime: 35,
    emoji: '🍋',
    ingredients: [
      { name: 'chicken breast', quantity: '6', unit: 'oz' },
      { name: 'asparagus', quantity: '1', unit: 'cup' },
      { name: 'zucchini', quantity: '1', unit: 'medium' },
      { name: 'lemon', quantity: '1', unit: 'medium' },
    ],
    steps: [
      'Preheat oven to 200°C.',
      'Arrange chicken and vegetables on a sheet pan, squeeze lemon over everything.',
      'Roast for 25–30 minutes until chicken is cooked through.',
    ],
  },
  {
    id: 'curated_baked_cod_packages',
    name: 'Baked Cod Packages',
    mealType: 'dinner',
    prepTime: 25,
    emoji: '🐟',
    ingredients: [
      { name: 'cod fillet', quantity: '6', unit: 'oz' },
      { name: 'cherry tomatoes', quantity: '0.5', unit: 'cup' },
      { name: 'spinach', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Place cod on a large piece of foil.',
      'Top with tomatoes and spinach, fold into a sealed packet.',
      'Bake at 200°C for 18–20 minutes.',
    ],
  },
  {
    id: 'curated_crispy_garlic_paprika_cod',
    name: 'Crispy Garlic & Paprika Cod',
    mealType: 'dinner',
    prepTime: 20,
    emoji: '🧄',
    ingredients: [
      { name: 'cod fillet', quantity: '6', unit: 'oz' },
      { name: 'smoked paprika', quantity: '1', unit: 'tsp' },
      { name: 'garlic powder', quantity: '0.5', unit: 'tsp' },
      { name: 'onion powder', quantity: '0.25', unit: 'tsp' },
      { name: 'green beans', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Rub cod with paprika, garlic powder, and onion powder.',
      'Spray with olive oil spray and bake at 220°C for 15 minutes.',
      'Steam green beans and serve alongside.',
    ],
  },
  {
    id: 'curated_chicken_fajita_bowl',
    name: 'Chicken Fajita Bowl',
    mealType: 'dinner',
    prepTime: 20,
    emoji: '🌮',
    ingredients: [
      { name: 'chicken breast strips', quantity: '6', unit: 'oz' },
      { name: 'bell peppers', quantity: '1', unit: 'cup' },
      { name: 'white onion', quantity: '0.5', unit: 'medium' },
      { name: 'fajita seasoning', quantity: '1', unit: 'tsp' },
      { name: 'romaine lettuce', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Season chicken strips with fajita spices and cook in a hot pan.',
      'Sauté bell peppers and onion until tender.',
      'Serve over a bed of romaine lettuce.',
    ],
  },
  {
    id: 'curated_shrimp_skewers',
    name: 'Shrimp Skewers',
    mealType: 'dinner',
    prepTime: 20,
    emoji: '🍤',
    ingredients: [
      { name: 'shrimp', quantity: '6', unit: 'oz' },
      { name: 'lime juice', quantity: '1', unit: 'tbsp' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
      { name: 'cauliflower rice', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Marinate shrimp in lime juice and cilantro for 15 minutes.',
      'Thread onto skewers and grill for 3–4 minutes per side.',
      'Serve over cauliflower rice.',
    ],
  },
  {
    id: 'curated_beef_broccoli',
    name: 'Beef & Broccoli',
    mealType: 'dinner',
    prepTime: 20,
    emoji: '🥦',
    ingredients: [
      { name: 'lean steak strips', quantity: '5', unit: 'oz' },
      { name: 'broccoli florets', quantity: '2', unit: 'cups' },
      { name: 'ginger', quantity: '0.5', unit: 'tsp' },
      { name: 'low-sodium soy sauce', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Stir-fry beef strips in a hot wok for 3 minutes.',
      'Add broccoli, ginger, and soy sauce.',
      'Cook for 5 more minutes and serve immediately.',
    ],
  },
  {
    id: 'curated_turkey_meatloaf',
    name: 'Turkey Meatloaf',
    mealType: 'dinner',
    prepTime: 55,
    emoji: '🍖',
    ingredients: [
      { name: 'lean ground turkey', quantity: '6', unit: 'oz' },
      { name: 'rolled oats', quantity: '3', unit: 'tbsp' },
      { name: 'white onion', quantity: '0.25', unit: 'cup' },
      { name: 'celery', quantity: '2', unit: 'stalks' },
    ],
    steps: [
      'Mix turkey, oats, diced onion, and celery.',
      'Shape into a loaf in a baking pan.',
      'Bake at 180°C for 45 minutes. Rest 5 minutes before slicing.',
    ],
  },
  {
    id: 'curated_white_fish_asparagus',
    name: 'White Fish & Asparagus',
    mealType: 'dinner',
    prepTime: 20,
    emoji: '🐠',
    ingredients: [
      { name: 'white fish fillet', quantity: '6', unit: 'oz' },
      { name: 'smoked paprika', quantity: '0.5', unit: 'tsp' },
      { name: 'asparagus spears', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Season fish with paprika.',
      'Bake fish and asparagus at 200°C for 15–18 minutes.',
    ],
  },
  {
    id: 'curated_lean_steak_night',
    name: 'Lean Steak Night',
    mealType: 'dinner',
    prepTime: 20,
    emoji: '🥩',
    ingredients: [
      { name: 'lean filet or sirloin steak', quantity: '5', unit: 'oz' },
      { name: 'mixed greens', quantity: '2', unit: 'cups' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Season steak with salt and pepper and sear for 3–4 minutes per side.',
      'Rest 5 minutes before slicing.',
      'Serve alongside mixed greens dressed with lemon juice.',
    ],
  },
  {
    id: 'curated_lemon_herb_baked_salmon',
    name: 'Lemon Herb Baked Salmon',
    mealType: 'dinner',
    prepTime: 25,
    emoji: '🐟',
    ingredients: [
      { name: 'salmon fillet', quantity: '6', unit: 'oz' },
      { name: 'fresh dill', quantity: '1', unit: 'tbsp' },
      { name: 'lemon', quantity: '1', unit: 'medium' },
      { name: 'asparagus spears', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Place salmon on a baking sheet, top with dill and lemon slices.',
      'Add asparagus to the pan.',
      'Bake at 200°C for 18–20 minutes.',
    ],
  },
  {
    id: 'curated_chicken_cacciatore',
    name: 'Chicken Cacciatore',
    mealType: 'dinner',
    prepTime: 40,
    emoji: '🍅',
    ingredients: [
      { name: 'chicken breast chunks', quantity: '6', unit: 'oz' },
      { name: 'diced tomatoes', quantity: '1', unit: 'cup' },
      { name: 'bell peppers', quantity: '1', unit: 'cup' },
      { name: 'mushrooms', quantity: '0.5', unit: 'cup' },
      { name: 'yellow onion', quantity: '0.25', unit: 'cup' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
    ],
    steps: [
      'Sauté onion, garlic, and peppers for 3 minutes.',
      'Add chicken and brown on all sides.',
      'Add tomatoes, mushrooms, oregano, and basil. Simmer for 25 minutes.',
    ],
  },
  {
    id: 'curated_spicy_peri_peri_chicken',
    name: 'Spicy Peri-Peri Chicken',
    mealType: 'dinner',
    prepTime: 30,
    emoji: '🔥',
    ingredients: [
      { name: 'chicken breast', quantity: '6', unit: 'oz' },
      { name: 'peri-peri chili sauce', quantity: '2', unit: 'tbsp' },
      { name: 'broccoli florets', quantity: '1.5', unit: 'cups' },
    ],
    steps: [
      'Coat chicken in peri-peri sauce and marinate 15 minutes.',
      'Grill chicken for 6–7 minutes per side.',
      'Roast broccoli at 200°C for 20 minutes and serve alongside.',
    ],
  },
  {
    id: 'curated_garlic_herb_chicken_skewers',
    name: 'Garlic Herb Chicken Skewers',
    mealType: 'dinner',
    prepTime: 25,
    emoji: '🍢',
    ingredients: [
      { name: 'chicken breast cubes', quantity: '6', unit: 'oz' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
      { name: 'bell peppers', quantity: '1', unit: 'cup' },
      { name: 'zucchini', quantity: '0.5', unit: 'medium' },
    ],
    steps: [
      'Marinate chicken in garlic and oregano for 15 minutes.',
      'Thread chicken and vegetables onto skewers.',
      'Grill for 12–15 minutes, turning occasionally.',
    ],
  },
  {
    id: 'curated_cajun_white_fish',
    name: 'Cajun White Fish',
    mealType: 'dinner',
    prepTime: 20,
    emoji: '🐡',
    ingredients: [
      { name: 'tilapia or cod fillet', quantity: '6', unit: 'oz' },
      { name: 'cajun seasoning', quantity: '1', unit: 'tsp' },
      { name: 'green beans', quantity: '1.5', unit: 'cups' },
    ],
    steps: [
      'Rub fish with cajun seasoning.',
      'Cook in a non-stick pan for 4 minutes per side.',
      'Steam green beans and serve alongside.',
    ],
  },
  {
    id: 'curated_turkey_kofta',
    name: 'Turkey Kofta',
    mealType: 'dinner',
    prepTime: 25,
    emoji: '🧆',
    ingredients: [
      { name: 'lean ground turkey', quantity: '6', unit: 'oz' },
      { name: 'fresh parsley', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '0.5', unit: 'tsp' },
      { name: 'coriander', quantity: '0.25', unit: 'tsp' },
      { name: 'cucumber', quantity: '0.5', unit: 'medium' },
    ],
    steps: [
      'Mix turkey with parsley, cumin, and coriander. Shape into logs around skewers.',
      'Grill for 10–12 minutes.',
      'Serve with a simple cucumber salad.',
    ],
  },
  {
    id: 'curated_spicy_shrimp_curry',
    name: 'Spicy Shrimp Curry',
    mealType: 'dinner',
    prepTime: 20,
    emoji: '🍛',
    ingredients: [
      { name: 'shrimp', quantity: '6', unit: 'oz' },
      { name: 'yellow curry powder', quantity: '1', unit: 'tsp' },
      { name: 'light coconut milk', quantity: '0.5', unit: 'cup' },
      { name: 'cauliflower florets', quantity: '1.5', unit: 'cups' },
    ],
    steps: [
      'Simmer cauliflower in coconut milk with curry powder for 10 minutes.',
      'Add shrimp and cook for 4–5 minutes until pink.',
      'Serve hot.',
    ],
  },
  {
    id: 'curated_mediterranean_baked_chicken',
    name: 'Mediterranean Baked Chicken',
    mealType: 'dinner',
    prepTime: 35,
    emoji: '🌿',
    ingredients: [
      { name: 'chicken breast', quantity: '6', unit: 'oz' },
      { name: 'artichoke hearts', quantity: '0.5', unit: 'cup' },
      { name: 'sun-dried tomatoes', quantity: '3', unit: 'tbsp' },
      { name: 'spinach', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Place chicken in a baking dish with artichokes, sun-dried tomatoes, and spinach.',
      'Season with salt, pepper, and herbs.',
      'Bake at 190°C for 25–28 minutes.',
    ],
  },
  {
    id: 'curated_lemon_pepper_tuna_steak',
    name: 'Lemon Pepper Tuna Steak',
    mealType: 'dinner',
    prepTime: 15,
    emoji: '🐟',
    ingredients: [
      { name: 'ahi tuna steak', quantity: '6', unit: 'oz' },
      { name: 'lemon pepper seasoning', quantity: '1', unit: 'tsp' },
      { name: 'spinach', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Season tuna with lemon pepper.',
      'Sear in a very hot pan for 90 seconds per side (rare center).',
      'Sauté spinach in the same pan and serve alongside.',
    ],
  },
  {
    id: 'curated_balsamic_glazed_steak',
    name: 'Balsamic Glazed Steak',
    mealType: 'dinner',
    prepTime: 25,
    emoji: '🥩',
    ingredients: [
      { name: 'lean sirloin steak', quantity: '5', unit: 'oz' },
      { name: 'balsamic vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'Brussels sprouts', quantity: '1.5', unit: 'cups' },
    ],
    steps: [
      'Halve Brussels sprouts and roast at 200°C for 20 minutes.',
      'Sear steak for 3–4 minutes per side, brush with balsamic glaze in last minute.',
      'Rest steak 5 minutes before slicing and serving.',
    ],
  },
  {
    id: 'curated_chicken_zucchini_boats',
    name: 'Chicken & Zucchini Boats',
    mealType: 'dinner',
    prepTime: 35,
    emoji: '🎃',
    ingredients: [
      { name: 'zucchini', quantity: '2', unit: 'large' },
      { name: 'diced chicken breast', quantity: '5', unit: 'oz' },
      { name: 'marinara sauce', quantity: '0.5', unit: 'cup' },
      { name: 'low-fat mozzarella', quantity: '3', unit: 'tbsp' },
    ],
    steps: [
      'Halve zucchini lengthwise and scoop out flesh.',
      'Mix chicken and marinara, fill the zucchini boats.',
      'Top with mozzarella and bake at 200°C for 20–25 minutes.',
    ],
  },

  // ── SNACK (4 options) ───────────────────────────────────────────────────────

  {
    id: 'curated_apple_peanut_butter',
    name: 'Apple & Peanut Butter',
    mealType: 'snack',
    prepTime: 2,
    emoji: '🍎',
    ingredients: [
      { name: 'apple', quantity: '1', unit: 'medium' },
      { name: 'natural peanut butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: ['Slice apple and serve with peanut butter for dipping.'],
  },
  {
    id: 'curated_hummus_veggies',
    name: 'Hummus & Veggie Sticks',
    mealType: 'snack',
    prepTime: 5,
    emoji: '🥕',
    ingredients: [
      { name: 'hummus', quantity: '3', unit: 'tbsp' },
      { name: 'carrot sticks', quantity: '1', unit: 'cup' },
      { name: 'cucumber sticks', quantity: '0.5', unit: 'cup' },
    ],
    steps: ['Arrange veggie sticks and serve with hummus for dipping.'],
  },
  {
    id: 'curated_greek_yogurt_berries',
    name: 'Greek Yogurt & Berries',
    mealType: 'snack',
    prepTime: 2,
    emoji: '🫐',
    ingredients: [
      { name: '0% Greek yogurt', quantity: '0.5', unit: 'cup' },
      { name: 'mixed berries', quantity: '0.25', unit: 'cup' },
    ],
    steps: ['Top yogurt with berries and serve.'],
  },
  {
    id: 'curated_hard_boiled_eggs',
    name: 'Hard-Boiled Eggs',
    mealType: 'snack',
    prepTime: 12,
    emoji: '🥚',
    ingredients: [
      { name: 'eggs', quantity: '2', unit: 'large' },
    ],
    steps: [
      'Place eggs in a pot, cover with cold water, and bring to a boil.',
      'Cook for 10 minutes, then cool in ice water before peeling.',
    ],
  },
];
